### ISSUE TITLE
4.2.0 - Firebase Runtime Crash on Samsung OS

### ISSUE THREAD

**Issue by lpalac4** [iovation/deviceprint-SDK-Android#8]
We're seeing a lot of runtime crashes in Firebase inside FraudForce and I'm hoping you have some tips on how to fix this.  We are seeing this on mostly Samsung devices on Android 9 and 10. 

fraudforce-lib-4.2.0-release
compileSdkVersion 29
targetSdkVersion 29

We've also seen this crash using the 4.1.1 release which prompted us to upgrade to try to address the problem.  We've tried to pass both the ApplicationContext as well as Activity/Fragment context to the FraudForceManager instance without luck.

![image](https://user-images.githubusercontent.com/5545895/102795936-1a829e80-4373-11eb-888b-3943c886a470.png)

Please let me know what other info I can add.

**Comment by DmitrijsD** [comment]
Crashes on Emulator 7.1.1 and other devices also

**Comment by ashley-campbell-iovation** [comment]
Hello! Does this problem exist in the absence of Firebase? If not, I suspect it may be a collision between the two obfuscated libraries. Because of this, I would recommend assuring your Proguard or Dexguard config files are set up appropriately as they may need to be updated. If you are still experiencing problems, please reach out to your integration engineer to escalate directly with our engineering team.

**Comment by DmitrijsD** [comment]
Fixed by running an initialization block on MainCoroutineDispatcher instead of IO
